sudo: required
services:
  - docker

before_install:
  - docker build -t kkarthik7/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kkarthik7/react-test npm test -- --coverage

after_success:
  - docker build -t kkarthik7/mclient ./client
  - docker build -t kkarthik7/mnginx ./nginx
  - docker build -t kkarthik7/mserver ./server
  - docker build -t kkarthik7/mworker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kkarthik7/mclient
  - docker push kkarthik7/mnginx
  - docker push kkarthik7/mserver
  - docker push kkarthik7/mworker
